### ISSUE TITLE
CLI Interface

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/snowball#1]
This application is going to need a CLI interface in order to configure it. Having external shell scripts seems like a lame way to do it, so I suggest we make it pretty.

As I see it, I figure we're going to need the following options:
* Maximum depth: how many pages from the see should the crawler continue through.
* Maximum pages: how many pages should the crawler scrape before it starts.
* Output directory: where should the saved pages be stored.
* Number of CPU threads: how many threads should be used by the application.
* Seed URL file: text file with seed URLs.

I think [this library](https://picocli.info/) looks good for creating a CLI frontend.

## Tasks

- [x] `--max-depth` (Integer, default 6): Maximum depth from see should the crawler travel.
- [x] `--max-pages` (Integer, default 10000): How many pages should be consumed before we exit.
- [x] `--output` (`java.nio.Path`): Directory to save HTML files to. Validate that this directory exists before running program.
- [x] `--threads` (Integer, default 4): Number of total program threads (1 for manager, 3 for worker).
- [x] `--seeds` (`java.nio.Path`, default to `seeds.txt`): Text file with seeds. One URL per line.
- [x] `--max-size`: Overrides `--max-pages`. Defaults to 20GB (20000).
- [x] Create entry point to application that consumes the previous arguments.
- [x] Call `Manager` class and pass application arguments (#2).
