### ISSUE TITLE
Manager

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/snowball#2]
This is the main part of the program. The entrypoint of the software calls this class, and this class in turn sets up the program and runs it.

## Components
- Input (inbound) URL queue with sanitized "safe" URLs.
- Output (outbound) URL queue with "potentially unsafe" URLs.
- Validate URLS
  - Removing URL parameters (~~page element IDs~~, URL POST parameters, anchors, etc.).
  - Ensure that URL hasn't been visited.

## Tasks
- [x] Load seeds from supplied seed file and create `URLTransaction` from those supplied URLs.
  - URL seeds are one per line.
  - Place directly in outbound queue.
- [x] Pop unsafe URL off outbound queue (as `URLTransaction<String>`).
  - [x] Clean URL (remove parameters, anchors, ~~set proper port~~, and protocol).
    - You might want to use `URLTransaction.copyToURL()` method which returns a  `URLTransaction<URL>` which you can clean and stuff. This method isn't safe, so any invalid URLs will throw an exception so you will need to handle this yourself. Just discard any URLs that trigger an exception.
  - [x] Check to see if URL has been visited (see #4).
  - [ ] Validate URL against `robots.txt` (see #6).
  - [x] Place URL on inbound queue.
