### ISSUE TITLE
Robots.txt Handler

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/snowball#6]
Check to make sure that a URL can be visited on the site and that it conforms to that domain's `robots.txt`.

## Components
- Domain lookup mechanism.
- Ability to get `robots.txt` for a domain that hasn't been discovered.
- URL validation mechanism that compares URL against `robots.txt`.

See [this library](https://github.com/pandzel/RobotsTxt) for a potential `robots.txt` validator.

## Tasks
- [x] Method to validate URL against `robots.txt` for a domain.
  - [x] Lookup URL in hashmap for `com.panforge.robotstxt.RobotsTxt` instance.
    - [x] Return true for all URLs for domain with missing `robots.txt`.
  - [x] Pass URL to `RobotsTxt` instance and check if it has access.
  - [x] Return result so that manager can make decision to remove/not remove from outbound queue.
- [x] Function to get `robots.txt` for domain that the application doesn't have an existing record of.
  - Handle 404 errors by making the storage value an `Optional<T>` and checking on lookup.
- [x] Unit tests.
